version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - uploads:/home/ubuntu/color-transfer/uploads
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  consumer:
    build: .
    command: ["python", "color_transfer.py"]
    volumes:
      - uploads:/home/ubuntu/color-transfer/uploads
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: "redis:alpine"

volumes:
  uploads: