version: '3'
services:
  web:
    image: "color"
    ports:
      - "8080:8080"
    volumes:
      - uploads:/home/ubuntu/color-transfer/uploads
      - db_sqlite:/home/ubuntu/color-transfer/db
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  consumer:
    image: "color"
    command: ["python", "color_transfer.py"]
    volumes:
      - uploads:/home/ubuntu/color-transfer/uploads
      - db_sqlite:/home/ubuntu/color-transfer/db
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: "redis:alpine"
    volumes:
      - redis:/data

volumes:
  redis:
  uploads:
  db_sqlite: